language: python

python:
  - "2.7"
  - "3.5"
  - "3.6"

env:
  - MYSQL_PACKAGE=pymysql
  - MYSQL_PACKAGE=mysqlclient

cache:
  pip: true
  directories:
    - $HOME/.cache/pypoetry

services:
  - mysql

addons:
  postgresql: '9.6'

install:
  - curl -fsS -o get-poetry.py https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py
  - python get-poetry.py --preview
  - if [[ $MYSQL_PACKAGE == 'pymysql' ]]; then poetry install --extras mysql-python --extras pgsql; fi
  - if [[ $MYSQL_PACKAGE == 'mysqlclient' ]]; then poetry install --extras mysql --extras pgsql; fi

script: pytest tests/

before_script:
  - psql -c 'create database orator_test;' -U postgres
  - mysql -e 'create database orator_test;'
